server:
  port: 8095

spring:
  profiles:
    active: local
  sql:
    init:
      mode: embedded
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:gwh
    username: pwaldorf
    password: pwaldorf
    databaseType: H2
    jpa-dialect: org.hibernate.dialect.H2Dialect
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
