
INSERT INTO rules (ruleset_name, rule_id, priority, condition_type, pass_action_type, fail_action_type, always_action_type, condition_context, condition, pass_context, pass, fail_context, fail, always_context, always, condition_class_name, pass_class_name, fail_class_name, always_class_name, condition_bean_name, condition_bean_method, pass_bean_name, pass_bean_method, fail_bean_name, fail_bean_method, always_bean_name, always_bean_method, description)
       VALUES (
       'NRT_RULESET_TEST1',
       'NRT_TEST1',
       '1',
       'MVEL',
       'MVEL',
       ' ',
       ' ',
       'Field1:Value1',
       'debitAmount < 10',
       ' ',
       'System.out.println("PJW MVEL")',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'Debit Amount greater than 10');

INSERT INTO rules (ruleset_name, rule_id, priority, condition_type, pass_action_type, fail_action_type, always_action_type, condition_context, condition, pass_context, pass, fail_context, fail, always_context, always, condition_class_name, pass_class_name, fail_class_name, always_class_name, condition_bean_name, condition_bean_method, pass_bean_name, pass_bean_method, fail_bean_name, fail_bean_method, always_bean_name, always_bean_method, description)
       VALUES (
       'NRT_RULESET_TEST1',
       'NRT_TEST11',
       '1',
       'SPRING',
       'MVEL',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'System.out.println("PJW MVEL")',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'sampleSpringRules',
       'isAdult',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'Debit Amount greater than 15');

-- *************************************************************************************************************************************************************************************
INSERT INTO rules (ruleset_name, rule_id, priority, condition_type, pass_action_type, fail_action_type, always_action_type, condition_context, condition, pass_context, pass, fail_context, fail, always_context, always, condition_class_name, pass_class_name, fail_class_name, always_class_name, condition_bean_name, condition_bean_method, pass_bean_name, pass_bean_method, fail_bean_name, fail_bean_method, always_bean_name, always_bean_method, description)
       VALUES (
       'NRT_RULESET_TEST1',
       'NRT_TEST2',
       '2',
       'SPRING',
       'SPRING',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'sampleSpringRules',
       'isAdult',
       'sampleSpringRules',
       'sayHello',
       ' ',
       ' ',
       ' ',
       ' ',
       'Debit Amount greater than 10');

-- *************************************************************************************************************************************************************************************
INSERT INTO rules (ruleset_name, rule_id, priority, condition_type, pass_action_type, fail_action_type, always_action_type, condition_context, condition, pass_context, pass, fail_context, fail, always_context, always, condition_class_name, pass_class_name, fail_class_name, always_class_name, condition_bean_name, condition_bean_method, pass_bean_name, pass_bean_method, fail_bean_name, fail_bean_method, always_bean_name, always_bean_method, description)
       VALUES (
       'NRT_RULESET_TEST1',
       'NRT_TEST3',
       '3',
       'JAVA',
       'JAVA',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'com.pw.rulesengine.samplerules.SampleJavaCondition',
       'com.pw.rulesengine.samplerules.SampleJavaAction',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       ' ',
       'Animal Name Tiger');
